language: python
python:
  - "2.7"
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
  - sudo sh -c "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' >> /etc/apt/sources.list"
  - sudo apt-get install mongodb-10gen
  - sudo apt-get install default-jre
  - sudo apt-get install gfortran libatlas-base-dev
  - sudo service mongodb start
install:
  - pip install numpy --use-mirrors
  - pip install -r requirements.pip --use-mirrors
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
script:
  - python manage.py test --noinput
  - ./js_tests/EnvJasmine/bin/run_all_tests.sh --configFile=../../js_tests/env_jasmine.conf.js --testDir=../../js_tests
notifications:
  irc: "irc.freenode.org#moditest"
